name: env_py-off-bgc
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - glob
  - xarray
  - dask
  - distributed
  - netcdf4
  - numpy
  - scipy
  - pandas
  - gsw
  - h5py
  - h5netcdf
  - bottleneck
  - copernicusmarine
  - taichi
  - pyyaml
  - cdsapi
