name: env_py-off-bgc
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - xarray
  - cartopy
  - dask
  - distributed
  - netcdf4
  - numba
  - numpy
  - scipy
  - pandas
  - gsw
  - matplotlib
  - ipykernel
  - taichi
  - zenodo_get
